# Generated by Django 2.2.8 on 2019-12-09 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StateChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('blocknumber', models.IntegerField()),
                ('sumstatechanges', models.IntegerField()),
                ('firings0count', models.IntegerField()),
                ('firings1count', models.IntegerField()),
                ('firings2count', models.IntegerField()),
                ('firings3count', models.IntegerField()),
                ('firings4count', models.IntegerField()),
                ('firings5count', models.IntegerField()),
                ('firings6count', models.IntegerField()),
                ('firings7count', models.IntegerField()),
                ('firings8count', models.IntegerField()),
                ('firings9count', models.IntegerField()),
                ('firings10count', models.IntegerField()),
                ('firings11count', models.IntegerField()),
                ('firings12count', models.IntegerField()),
                ('firings13count', models.IntegerField()),
                ('wiringscount', models.IntegerField()),
                ('unknownscount', models.IntegerField()),
            ],
        ),
    ]
