# Generated by Django 3.0 on 2020-01-31 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('blocknumber', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('fullyprocessed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='BurnTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('blocknumber', models.IntegerField()),
                ('getburned', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='CryptoPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=3)),
                ('price_eur', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='StateChange',
            fields=[
                ('hash', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('previoushash', models.CharField(max_length=100)),
                ('statechangetype', models.CharField(choices=[('f', 'New firing'), ('w', 'New wiring')], max_length=1)),
                ('statechangesubtype', models.IntegerField(choices=[(0, 'Ticket or Wiring created'), (1, 'Ticket blocked'), (2, 'Ticket sold on primary market'), (3, 'Ticket sold on secondary market'), (4, 'Ticket bought back by organizer'), (5, 'Ticket cancelled'), (6, 'Ticket put for sale'), (7, 'Show cancelled'), (8, 'Ticket not resold'), (9, 'Ticket not sold on primary market'), (10, 'Ticket sold on the secondary market'), (11, 'Ticket scanned'), (12, 'Show over'), (13, 'Ticket unblocked')])),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statechanges.Block')),
            ],
        ),
    ]
