# Generated by Django 3.0 on 2020-01-24 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statechanges', '0002_cryptoprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='BurnTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('blocknumber', models.IntegerField()),
                ('getburned', models.FloatField()),
            ],
        ),
    ]
