# Generated by Django 3.0.7 on 2020-06-17 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statechanges', '0003_auto_20200302_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='f999sum',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='block',
            name='ipfshash',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='event',
            name='f999sum',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='statechange',
            name='firing',
            field=models.IntegerField(choices=[(0, 'Ticket or Wiring created'), (1, 'Ticket blocked'), (2, 'Ticket sold on primary market'), (3, 'Ticket sold on secondary market'), (4, 'Ticket bought back by organizer'), (5, 'Ticket cancelled'), (6, 'Ticket put for sale'), (7, 'Show cancelled'), (8, 'Ticket not resold'), (9, 'Ticket not sold on primary market'), (10, 'Ticket sold on the secondary market'), (11, 'Ticket scanned'), (12, 'Show over'), (13, 'Ticket unblocked'), (999, 'Error')]),
        ),
    ]
