# Generated by Django 3.0.7 on 2020-08-03 13:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('statechanges', '0004_auto_20200617_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='lastupdate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
