# Generated by Django 3.0.7 on 2020-06-17 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statechanges', '0004_auto_20200617_0834'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='ipfshash',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
