# Generated by Django 3.0.7 on 2020-07-14 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GETAddress',
            fields=[
                ('address', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('balance', models.DecimalField(decimal_places=18, default=0, max_digits=26)),
                ('lastupdate', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GETPeriodSummary',
            fields=[
                ('periodname', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('activewallets', models.IntegerField()),
                ('transactions', models.IntegerField()),
                ('getdistributed', models.DecimalField(decimal_places=2, max_digits=12)),
                ('exetherdeltabalance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('excoinonebalance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('exidexbalance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('exliquidbalance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('exuniswapbalance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('exhotbitbalance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('extotalbalance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fullyprocessed', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='TAppStatus',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Tblock',
            fields=[
                ('blocknumber', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='GETTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transactionhash', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=18, max_digits=26)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hodlers.Tblock')),
                ('fromaddress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fromtransaction', to='hodlers.GETAddress')),
                ('toaddress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='totransaction', to='hodlers.GETAddress')),
            ],
        ),
    ]
